### ISSUE TITLE
backports.tarfile

### ISSUE THREAD

**Issue by shernyukov** [varioustoxins/NEF-Pipelines#4]
In the script "install_nef_pipelines" in cppnmr3/bin path, it needs to add the installation with "-m pip" of the "backports.tarfile" package for successful compilation:
`"${CONDA_PYTHON3}" -m pip install --upgrade wheel setuptools backports.tarfile`
 Otherwise, the installation is interrupted with the following error:
"ERROR: Can not execute `setup.py` since setuptools is not available in the build environment"

**Comment by varioustoxins** [comment]
Thank you so much for that, i have trying to sort what causes that a while i will test it soon!

**Comment by varioustoxins** [comment]
Could you let me know what is and version you are on?

**Comment by varioustoxins** [comment]
Sorry could you say which os and version macOS auto corrected me!

**Comment by shernyukov** [comment]
My os is OpenSUSE Leap 15.6, which is linux distro.




чт, 19 сент. 2024 г. в 23:15, varioustoxins ***@***.***>:

**Comment by varioustoxins** [comment]
@shernyukov  Thank you, I have implemented the fix and it seems to work. However, do you follow why this is suddenly needed when installing using pip3, I can't seem to find more details.... I presume an update to setup tools uses too modern a version of tarfile for the one in conda?

**Comment by shernyukov** [comment]
@varioustoxins Unfortunately I don't have the opportunity to deal with this, but I think judging by the symptoms it is similar to this [case](https://github.com/pypa/setuptools/issues/4508).
At least an attempt to import gives the same diagnostics:
```
limor5.andrew:~/opt/ccpnmr3.2.0/bin>$CONDA_PYTHON3 
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/__init__.py", line 27, in <module>
    from .dist import Distribution
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/dist.py", line 18, in <module>
    from . import (
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/_entry_points.py", line 6, in <module>
    from jaraco.text import yield_lines
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/_vendor/jaraco/text/__init__.py", line 12, in <module>
    from jaraco.context import ExceptionTrap
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/_vendor/jaraco/context.py", line 17, in <module>
    from backports import tarfile
ImportError: cannot import name 'tarfile' from 'backports' (/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/backports/__init__.py)
>>> 
```

**Comment by varioustoxins** [comment]
Anyway I have sent the fix to the ccpn team hopefully they will have it in soon…


Dr Gary S Thompson NMR Facility Manager
CCPN CoI & Working Group Member
Wellcome Trust Biomolecular NMR Facility
School of Biosciences,  Division of Natural Sciences
University of Kent,  Canterbury,  Kent,  England,  CT2 7NZ

☎:01227 82 7117
✉️: ***@***.***
orchid: orcid.org/0000-0001-9399-7636

On 24 Sep 2024, at 10:08, shernyukov ***@***.***> wrote:


CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.




@varioustoxins<https://github.com/varioustoxins> Unfortunately I don't have the opportunity to deal with this, but I think judging by the symptoms it is similar to this case<https://github.com/pypa/setuptools/issues/4508>.
At least an attempt to import gives the same diagnostics:

limor5.andrew:~/opt/ccpnmr3.2.0/bin>$CONDA_PYTHON3
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/__init__.py", line 27, in <module>
    from .dist import Distribution
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/dist.py", line 18, in <module>
    from . import (
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/_entry_points.py", line 6, in <module>
    from jaraco.text import yield_lines
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/_vendor/jaraco/text/__init__.py", line 12, in <module>
    from jaraco.context import ExceptionTrap
  File "/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/setuptools/_vendor/jaraco/context.py", line 17, in <module>
    from backports import tarfile
ImportError: cannot import name 'tarfile' from 'backports' (/home/andrew/opt/ccpnmr3.2.0/miniconda/lib/python3.10/site-packages/backports/__init__.py)
