### ISSUE TITLE
python3.12

### ISSUE THREAD

**Issue by Gerardwx** [varioustoxins/NEF-Pipelines#6]
This doesn't seem to work with python3.12. It works with python3.11, so we're using that.

Python3.12 install error: 
lugin nef_pipelines.tools.help
Traceback (most recent call last):
  File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/pynmrstar/__init__.py", line 15, in <module>
    import cnmrstar
ModuleNotFoundError: No module named 'cnmrstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/pynmrstar/__init__.py", line 18, in <module>
    import pynmrstar.cnmrstar as cnmrstar
ModuleNotFoundError: No module named 'pynmrstar.cnmrstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/nef_pipelines/main.py", line 117, in main
    import_module(module_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/nef_pipelines/tools/help/__init__.py", line 14, in <module>
    import nef_pipelines.tools.help.about  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/nef_pipelines/tools/help/about.py", line 8, in <module>
    from nef_pipelines.lib.util import get_version
  File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/nef_pipelines/lib/util.py", line 29, in <module>
    from pynmrstar import Entry, Loop, Saveframe
  File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/pynmrstar/__init__.py", line 23, in <module>
    raise ImportError('Could not import cnmrstar sub-module! Your installation appears to be broken.')
ImportError: Could not import cnmrstar sub-module! Your installation appears to be broken.
...

**Comment by varioustoxins** [comment]
Hi Gerardwx

Thanks for letting me know about that, I have tested installation under 12.x in gihub actions

 https://github.com/varioustoxins/NEF-Pipelines/actions/runs/11116703228


and it works there so it must be dependant on a particular linux distribution, I will have a look at what you are using and and try and reproduce. However, as you can see it should work across all platforms and python 3.8-3.12 (though I will soon drop 3.8 support* and  will adopt 3.13) so 3.11 should be fine

Also thanks for the pull requests I will have a look at those (especially the typo ;-) ! ) when get back from holiday

regards
Gary



* I will continue to test against 3.8 while its available on GitHub but will discontinue support if it interferes with new features and the libraries Want to use.

Dr Gary S Thompson NMR Facility Manager
CCPN CoI & Working Group Member
Wellcome Trust Biomolecular NMR Facility
School of Biosciences,  Division of Natural Sciences
University of Kent,  Canterbury,  Kent,  England,  CT2 7NZ

☎:01227 82 7117
✉️: ***@***.***
orchid: orcid.org/0000-0001-9399-7636

On 4 Oct 2024, at 14:41, Gerardwx ***@***.***> wrote:


CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.




This doesn't seem to work with python3.12. It works with python3.11, so we're using that.

Python3.12 install error:
lugin nef_pipelines.tools.help
Traceback (most recent call last):
File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/pynmrstar/init.py", line 15, in
import cnmrstar
ModuleNotFoundError: No module named 'cnmrstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/pynmrstar/init.py", line 18, in
import pynmrstar.cnmrstar as cnmrstar
ModuleNotFoundError: No module named 'pynmrstar.cnmrstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/nef_pipelines/main.py", line 117, in main
import_module(module_name)
File "/usr/lib/python3.12/importlib/init.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1387, in _gcd_import
File "", line 1360, in _find_and_load
File "", line 1331, in _find_and_load_unlocked
File "", line 935, in _load_unlocked
File "", line 995, in exec_module
File "", line 488, in _call_with_frames_removed
File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/nef_pipelines/tools/help/init.py", line 14, in
import nef_pipelines.tools.help.about # noqa: F401
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/nef_pipelines/tools/help/about.py", line 8, in
from nef_pipelines.lib.util import get_version
File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/nef_pipelines/lib/util.py", line 29, in
from pynmrstar import Entry, Loop, Saveframe
File "/usr/software/nefpipelines/venv/lib/python3.12/site-packages/pynmrstar/init.py", line 23, in
raise ImportError('Could not import cnmrstar sub-module! Your installation appears to be broken.')
ImportError: Could not import cnmrstar sub-module! Your installation appears to be broken.
...

**Comment by Gerardwx** [comment]
It's specific to Ubuntu20 installing python3.12 out of the deadsnakes PPA. It works fine on Ubuntu 22 and Ubuntu 24.

**Comment by varioustoxins** [comment]
Thanks!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
